# Generated by Django 4.2 on 2023-05-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddInsrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=100)),
                ('instrument_desc', models.TextField()),
                ('instrument_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
