# Generated by Django 4.2 on 2023-05-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentapp', '0002_addinsrument_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addinsrument',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
