# Generated by Django 4.2 on 2023-05-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentapp', '0004_alter_addinsrument_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinsrument',
            name='instrument_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
