# Generated by Django 4.2 on 2023-05-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentapp', '0005_alter_addinsrument_instrument_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinsrument',
            name='instrument_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
