# Generated by Django 4.2 on 2023-05-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentapp', '0007_bookinstrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstrument',
            name='iname',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
