# Generated by Django 4.2 on 2023-05-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentapp', '0009_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstrument',
            name='Aprove',
            field=models.BooleanField(default=False, verbose_name='Approve'),
        ),
        migrations.AlterField(
            model_name='approve',
            name='approve',
            field=models.BooleanField(default=False, verbose_name='Approve'),
        ),
    ]
